import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import QueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Link href={"/about"}>about</Link>
          <Link href={"/report"}>report</Link>
          <Link href={"/todo-csr"}>todo-CSR</Link>
          <Link href={"/todo-ssr"}>todo-SSR</Link>
        </div>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
